{% set name = "nats-py" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb1097db8b520bb4c8f5ad51340ca54d9fa54dbfc4ecc81c3625ef80994b6100

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - nats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nats-io/nats.py
  doc_url: https://nats-io.github.io/nats.py/
  summary: NATS client for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
