schema_version: 1

context:
  name: nats-py
  version: "2.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 2981ca4b63b8266c855573fa7871b1be741f1889fd429ee657e5ffc0971a38a1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - nats
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: NATS client for Python
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/nats-io/nats.py
  documentation: https://nats-io.github.io/nats.py/

extra:
  recipe-maintainers:
    - carlodri
